live_config_reload = true

[window]
decorations = "None"
opacity = 0.88
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
padding = { x = 0, y = 0 }

[font]
size = 14.0
offset = { y = 2 }
[font.normal]
family = "Hack Nerd Font"

[colors]
[colors.primary]
background = "#1e1e1e"
