theme = "dark_plus_bar"

[editor]
# line-number = "relative"
completion-trigger-len = 1
scrolloff = 3
cursorline = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
C-x = ":bc"
C-h = "jump_view_left"
C-l = "jump_view_right"
L = "goto_next_buffer"
H = "goto_previous_buffer"
C-g = [
  ":sh meld . &",
]
C-q = "wclose"
